---
# tasks file for docker_setup

- name: pull source code
  ansible.builtin.git:
    repo: 'https://github.com/Akshat-pixel/pipelinePrac.git'
    dest: ./pipelinePrac

- name: Download latest artifact from Nexus
  get_url:
    url: "{{ artifact_url }}"
    dest: /home/ubuntu/pipelinePrac/target/vproapp.war
    mode: '644'
    force: yes

- name: Start the container
  ansible.builtin.shell:
    cmd: docker compose up -d
    chdir: /home/ubuntu/pipelinePrac/
